// Auto-generated by extract-coords.js — 2026-03-08
// WGS84 lat/lng for all Saint Rose properties
// source: 'parcel' = Albany parcel geometry centroid (UTM 18N → WGS84)
//         'interpolated' = linear interpolation between street neighbours
//         'campus-fallback' = defaulted to campus centre

const COORDS_DATA = {
  "1000-madison-avenue-administration-center": {
    "lat": 42.663266,
    "lng": -73.78852,
    "source": "parcel"
  },
  "1001-madison-avenue-scanlan-hall": {
    "lat": 42.664072,
    "lng": -73.787242,
    "source": "parcel"
  },
  "1002-madison-avenue-massry-center-for-the-arts": {
    "lat": 42.663635,
    "lng": -73.78799,
    "source": "parcel"
  },
  "1006-madison-avenue": {
    "lat": 42.663693,
    "lng": -73.788325,
    "source": "parcel"
  },
  "1009-madison-avenue-thelma-p-lally-school-of-education": {
    "lat": 42.664424,
    "lng": -73.78754,
    "source": "parcel"
  },
  "1020-madison-avenue": {
    "lat": 42.663975,
    "lng": -73.788972,
    "source": "parcel"
  },
  "178-partridge-street": {
    "lat": 42.66348,
    "lng": -73.783003,
    "source": "parcel"
  },
  "186-partridge-street": {
    "lat": 42.663402,
    "lng": -73.783085,
    "source": "parcel"
  },
  "188-partridge-street": {
    "lat": 42.663263,
    "lng": -73.783102,
    "source": "parcel"
  },
  "190-partridge-street-health-services": {
    "lat": 42.66318,
    "lng": -73.783189,
    "source": "parcel"
  },
  "198-partridge-street": {
    "lat": 42.662926,
    "lng": -73.783456,
    "source": "parcel"
  },
  "200-202-partridge-street": {
    "lat": 42.662871,
    "lng": -73.783626,
    "source": "parcel"
  },
  "204-206-partridge-street": {
    "lat": 42.662756,
    "lng": -73.783635,
    "source": "parcel"
  },
  "208-210-partridge-street": {
    "lat": 42.662618,
    "lng": -73.783877,
    "source": "parcel"
  },
  "212-214-partridge-street-golub-mccarthy-hall": {
    "lat": 42.662444,
    "lng": -73.783884,
    "source": "parcel"
  },
  "340-western-avenue-security-headquarters": {
    "lat": 42.663218,
    "lng": -73.782212,
    "source": "parcel"
  },
  "350-western-avenue-kelly-hall": {
    "lat": 42.663417,
    "lng": -73.783364,
    "source": "parcel"
  },
  "354-western-avenue-kateri-hall": {
    "lat": 42.663528,
    "lng": -73.783437,
    "source": "parcel"
  },
  "358-western-avenue-collins-hall": {
    "lat": 42.663566,
    "lng": -73.783556,
    "source": "parcel"
  },
  "366a-western-avenue-alumni-hall": {
    "lat": 42.663342,
    "lng": -73.783847,
    "source": "parcel"
  },
  "366b-western-avenue-lima-hall": {
    "lat": 42.663342,
    "lng": -73.783847,
    "source": "parcel"
  },
  "374-western-avenue-hahn-hall": {
    "lat": 42.663718,
    "lng": -73.784034,
    "source": "parcel"
  },
  "380-western-avenue-mccormick-hall": {
    "lat": 42.663813,
    "lng": -73.784333,
    "source": "parcel"
  },
  "384-western-avenue-lourdes-hall": {
    "lat": 42.663748,
    "lng": -73.784495,
    "source": "parcel"
  },
  "399-western-avenue-cabrini-hall": {
    "lat": 42.664727,
    "lng": -73.785321,
    "source": "parcel"
  },
  "405-western-avenue-keeshan-hall": {
    "lat": 42.66481,
    "lng": -73.785758,
    "source": "parcel"
  },
  "415-western-avenue-avila-hall": {
    "lat": 42.66481,
    "lng": -73.785758,
    "source": "parcel"
  },
  "432-western-avenue-albertus-hall": {
    "lat": 42.664351,
    "lng": -73.786552,
    "source": "parcel"
  },
  "442-western-avenue-dolan-hall": {
    "lat": 42.664496,
    "lng": -73.78689,
    "source": "parcel"
  },
  "444-western-avenue-marcelle-hall": {
    "lat": 42.664586,
    "lng": -73.786985,
    "source": "parcel"
  },
  "450-western-avenue-griffin-hall": {
    "lat": 42.664647,
    "lng": -73.787071,
    "source": "parcel"
  },
  "454-western-avenue-soulier-hall": {
    "lat": 42.664667,
    "lng": -73.787256,
    "source": "parcel"
  },
  "458-western-avevue": {
    "lat": 42.664653,
    "lng": -73.78742,
    "source": "parcel"
  },
  "460-western-avenue": {
    "lat": 42.664723,
    "lng": -73.787565,
    "source": "parcel"
  },
  "464-western-avenue": {
    "lat": 42.664796,
    "lng": -73.787658,
    "source": "parcel"
  },
  "908-910-madison-avenue": {
    "lat": 42.66179,
    "lng": -73.78452,
    "source": "parcel"
  },
  "912-914-madison-avenue": {
    "lat": 42.661875,
    "lng": -73.784669,
    "source": "parcel"
  },
  "917-madison-avenue-rooney-hall": {
    "lat": 42.662215,
    "lng": -73.78415,
    "source": "parcel"
  },
  "921-madison-avenue": {
    "lat": 42.66267,
    "lng": -73.784179,
    "source": "parcel"
  },
  "923-madison-avenue-charter-hall": {
    "lat": 42.66279,
    "lng": -73.784484,
    "source": "parcel"
  },
  "930-madison-avenue-centennial-hall": {
    "lat": 42.661714,
    "lng": -73.785496,
    "source": "parcel"
  },
  "935-madison-avenue-fontebonne-hall": {
    "lat": 42.662887,
    "lng": -73.784655,
    "source": "parcel"
  },
  "940-madison-avenue": {
    "lat": 42.662234,
    "lng": -73.785776,
    "source": "parcel"
  },
  "944-madison-avenue-carey-hall": {
    "lat": 42.662392,
    "lng": -73.785825,
    "source": "parcel"
  },
  "946-madison-avenue": {
    "lat": 42.662414,
    "lng": -73.786052,
    "source": "parcel"
  },
  "947-madison-avenue-madison-hall": {
    "lat": 42.663109,
    "lng": -73.785253,
    "source": "parcel"
  },
  "950-madison-avenue": {
    "lat": 42.662414,
    "lng": -73.786052,
    "source": "parcel"
  },
  "956-madison-avenue": {
    "lat": 42.662449,
    "lng": -73.786273,
    "source": "parcel"
  },
  "959-madison-avenue-interfaith-sanctuary": {
    "lat": 42.663281,
    "lng": -73.785566,
    "source": "parcel"
  },
  "963-madison-avenue-wellworth-hall": {
    "lat": 42.663344,
    "lng": -73.785776,
    "source": "parcel"
  },
  "967-madison-avenue-casey-hall": {
    "lat": 42.663455,
    "lng": -73.785971,
    "source": "parcel"
  },
  "968-madison-avenue": {
    "lat": 42.662819,
    "lng": -73.786764,
    "source": "parcel"
  },
  "971-madison-avenue-gibbons-hall": {
    "lat": 42.663547,
    "lng": -73.786132,
    "source": "parcel"
  },
  "979-madison-avenue-moran-hall": {
    "lat": 42.66385,
    "lng": -73.786434,
    "source": "parcel"
  },
  "993-madison-avenue-science-center": {
    "lat": 42.663965,
    "lng": -73.786989,
    "source": "parcel"
  },
  "996-madison-avenue-hearst-center-for-communications-and-interactive-media": {
    "lat": 42.662806,
    "lng": -73.787489,
    "source": "parcel"
  },
  "368-western-avenue-delaney-hall": {
    "lat": 42.663436,
    "lng": -73.783894,
    "source": "interpolated"
  },
  "376-western-ave-cullen-hall": {
    "lat": 42.663749,
    "lng": -73.784134,
    "source": "interpolated"
  },
  "392-western-avenue-neil-hellman-library": {
    "lat": 42.66427,
    "lng": -73.784935,
    "source": "interpolated"
  },
  "401-western-avenue": {
    "lat": 42.664755,
    "lng": -73.785467,
    "source": "interpolated"
  },
  "407-western-avenue-medaille-hall": {
    "lat": 42.66481,
    "lng": -73.785758,
    "source": "interpolated"
  },
  "919-madison-avenue-desales-hall": {
    "lat": 42.662443,
    "lng": -73.784164,
    "source": "interpolated"
  },
  "919r-madison-avenue-maintenance": {
    "lat": 42.662443,
    "lng": -73.784164,
    "source": "interpolated"
  },
  "939-941-943-madison-avenue-riley-carondelet-cavanaugh-halls": {
    "lat": 42.662365,
    "lng": -73.785552,
    "source": "interpolated"
  },
  "953-madison-avenue-quillian-hall": {
    "lat": 42.662431,
    "lng": -73.786163,
    "source": "interpolated"
  },
  "972-madison-avenue": {
    "lat": 42.663585,
    "lng": -73.78617,
    "source": "interpolated"
  },
  "974-madison-avenue": {
    "lat": 42.663661,
    "lng": -73.786245,
    "source": "interpolated"
  },
  "985-madison-avenue-st-joseph-hall": {
    "lat": 42.6639,
    "lng": -73.786672,
    "source": "interpolated"
  },
  "994-madison-avenue-huether-school-of-business": {
    "lat": 42.663579,
    "lng": -73.787156,
    "source": "interpolated"
  }
};
